# coding=utf-8

from wikilife_biz.tests.services.user.base_user_test import BaseUserTest
from wikilife_biz.services.user.user_service import UserService


class UserServiceTest(BaseUserTest):

    def test_foo(self):
        assert True

    """
    def test_create_autogenerated_user(self):
        logger = self.get_logger()
        self.db = self.get_conn().test_user_service
        self.get_conn().drop_database("test_user_service")
        user_mgr = None
        self.user_srv = UserService(logger, user_mgr)
        user_name_prefix = "test_"

        created_user = self.user_srv.create_autogenerated_user(user_name_prefix)

        assert created_user != None
        assert created_user["user_name"].startswith(user_name_prefix + "auto_")
        assert self.db.users.find_one({'user_id': created_user["user_id"]})
    """

